name: Data Pipeline

on:
  schedule:
    - cron: '0 0 1 */3 *' # Runs quarterly
  workflow_dispatch: # Allows manual triggering

jobs:
  data_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pull data
      run: python callreq.py

    - name: Process data
      run: python processing.py

    - name: Run tests
      run: pytest tests/

    - name: Save to Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        kaggle datasets version -p ../data -m "Updated data"

    - name: Notify Slack
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Data pipeline completed successfully!"}' $SLACK_WEBHOOK_URL

